#!/usr/bin/env python3
"""
Generate ECHO-branded bitmap C header files for the ECHO firmware.

Replaces TRMNL logo bitmaps with ECHO wordmark bitmaps, encoded in
bb_epaper Group5 (G5) compressed format with the BB_BITMAP header.

Usage:
    python3 echo/generate_bitmaps.py

Dependencies:
    pip install Pillow qrcode
"""

import struct
import os
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

try:
    import qrcode
except ImportError:
    print("ERROR: qrcode not installed. Run: pip install qrcode")
    raise

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

SCRIPT_DIR = Path(__file__).parent
OUTPUT_DIR = SCRIPT_DIR / "generated"

# Bitmap specs matching originals
BITMAPS = {
    "logo_big":    {"width": 640, "height": 640, "var": "logo_big",    "file": "logo_big.h"},
    "logo_medium": {"width": 240, "height": 240, "var": "logo_medium", "file": "logo_medium.h"},
    "logo_small":  {"width": 86,  "height": 86,  "var": "logo_small",  "file": "logo_small.h"},
}

QR_SPEC = {
    "width": 66, "height": 66,
    "var": "wifi_failed_qr",
    "file": "wifi_failed_qr.h",
    "url": "https://shadowlab.cc/echo",
}

HEADER_COMMENT = "// Generated by echo/generate_bitmaps.py — ECHO 0.0.1-alpha"

# BB_BITMAP marker (little-endian 0xBBBF)
BB_BITMAP_MARKER = 0xBBBF

# ---------------------------------------------------------------------------
# G5 Encoder (Python port of Larry Bank's g5enc.inl)
# ---------------------------------------------------------------------------

# Number of consecutive 1-bits from MSB in a byte
_bitcount = [0]*256
for _i in range(256):
    _c = 0
    for _b in range(7, -1, -1):
        if _i & (1 << _b):
            _c += 1
        else:
            break
    _bitcount[_i] = _c

# Vertical code table: (code, length) for V(-3)..V(+3)
_vtable = [
    (3, 7),   # V(-3) = 0000011
    (3, 6),   # V(-2) = 000011
    (3, 3),   # V(-1) = 011
    (1, 1),   # V(0)  = 1
    (2, 3),   # V(1)  = 010
    (2, 6),   # V(2)  = 000010
    (2, 7),   # V(3)  = 0000010
]

HORIZ_SHORT_SHORT = 0
HORIZ_SHORT_LONG = 1
HORIZ_LONG_SHORT = 2
HORIZ_LONG_LONG = 3

MAX_IMAGE_FLIPS = 512


class G5BitWriter:
    """Buffered bit writer matching G5ENCInsertCode / G5ENCFlushBits."""
    def __init__(self):
        self.buf = bytearray()
        self.bits = 0        # 32-bit accumulator
        self.bit_off = 0     # bits used in accumulator

    def insert(self, code: int, length: int):
        if (self.bit_off + length) > 32:
            self.bits |= (code >> (self.bit_off + length - 32)) & 0xFFFFFFFF
            # Write 4 bytes big-endian
            self.buf.extend(self.bits.to_bytes(4, 'big'))
            self.bits = (code << (64 - self.bit_off - length)) & 0xFFFFFFFF
            self.bit_off = self.bit_off + length - 32
        else:
            self.bits |= (code << (32 - self.bit_off - length)) & 0xFFFFFFFF
            self.bit_off += length

    def flush(self):
        while self.bit_off >= 8:
            self.buf.append((self.bits >> 24) & 0xFF)
            self.bits = (self.bits << 8) & 0xFFFFFFFF
            self.bit_off -= 8
        if self.bit_off:
            self.buf.append((self.bits >> 24) & 0xFF)
        self.bit_off = 0
        self.bits = 0


def _encode_line_to_flips(pixel_bytes: bytes, xsize: int) -> list:
    """Convert a line of 1-bpp MSB-first pixels to run-end positions."""
    flips = []
    byte_count = (xsize + 7) >> 3
    idx = 0
    c = pixel_bytes[idx] if idx < len(pixel_bytes) else 0
    idx += 1
    byte_count -= 1
    cbits = 8
    run_len = 0
    x = 0
    xborder = xsize

    while byte_count >= 0:
        if len(flips) >= MAX_IMAGE_FLIPS - 4:
            break
        # Count white (1-bits from MSB)
        i = _bitcount[c & 0xFF]
        run_len += i
        c = (c << i) & 0xFF
        cbits -= i
        if cbits <= 0:
            run_len += cbits
            cbits = 8
            if byte_count > 0:
                c = pixel_bytes[idx] if idx < len(pixel_bytes) else 0
                idx += 1
            else:
                c = 0
            byte_count -= 1
            continue
        # Flip to count black
        c = (~c) & 0xFF
        # Store white run end
        xborder -= run_len
        if xborder < 0:
            run_len += xborder
            break
        x += run_len
        flips.append(x)
        run_len = 0

        # Count black (which are now 1-bits after flip)
        while True:
            i = _bitcount[c & 0xFF]
            run_len += i
            c = (c << i) & 0xFF
            cbits -= i
            if cbits <= 0:
                run_len += cbits
                cbits = 8
                if byte_count > 0:
                    c = pixel_bytes[idx] if idx < len(pixel_bytes) else 0
                    idx += 1
                    c = (~c) & 0xFF
                else:
                    c = 0
                byte_count -= 1
                if byte_count < 0:
                    break
                continue
            break

        # Flip back to white
        c = (~c) & 0xFF
        # Store black run end
        xborder -= run_len
        if xborder < 0:
            run_len += xborder
            break
        x += run_len
        flips.append(x)
        run_len = 0

    # Terminate with multiple xsize entries
    for _ in range(4):
        flips.append(xsize)

    return flips


def g5_encode(pixel_rows: list, width: int, height: int) -> bytes:
    """
    Encode a 1-bpp image using G5 compression.

    pixel_rows: list of bytes objects, one per row, MSB-first 1-bpp.
                White pixels = 1, Black pixels = 0.
    Returns: compressed G5 data (without the 8-byte BB_BITMAP header).
    """
    iHLen = (width - 1).bit_length()  # bits needed for longest run

    bw = G5BitWriter()

    # Reference line starts as all-white (no flips, just xsize markers)
    ref_flips = [width] * MAX_IMAGE_FLIPS

    for y in range(height):
        cur_flips = _encode_line_to_flips(pixel_rows[y], width)

        # Pad cur_flips if needed
        while len(cur_flips) < 8:
            cur_flips.append(width)

        # G5 encode this line
        a0 = 0
        iCur = 0
        iRef = 0

        while a0 < width:
            b1 = ref_flips[iRef] if iRef < len(ref_flips) else width
            b2 = ref_flips[iRef + 1] if (iRef + 1) < len(ref_flips) else width
            a1 = cur_flips[iCur] if iCur < len(cur_flips) else width

            if b2 < a1:
                # Pass mode
                a0 = b2
                iRef += 2
                bw.insert(1, 4)  # Pass code = 0001
            else:
                dx = b1 - a1
                if dx > 3 or dx < -3:
                    # Horizontal mode
                    bw.insert(1, 3)  # Horizontal code = 001
                    run1 = cur_flips[iCur] - a0
                    a2 = cur_flips[iCur + 1] if (iCur + 1) < len(cur_flips) else width
                    run2 = a2 - cur_flips[iCur]

                    if run1 < 8:
                        if run2 < 8:
                            bw.insert(HORIZ_SHORT_SHORT, 2)
                            bw.insert(run1, 3)
                            bw.insert(run2, 3)
                        else:
                            bw.insert(HORIZ_SHORT_LONG, 2)
                            bw.insert(run1, 3)
                            bw.insert(run2, iHLen)
                    else:
                        if run2 < 8:
                            bw.insert(HORIZ_LONG_SHORT, 2)
                            bw.insert(run1, iHLen)
                            bw.insert(run2, 3)
                        else:
                            bw.insert(HORIZ_LONG_LONG, 2)
                            bw.insert(run1, iHLen)
                            bw.insert(run2, iHLen)

                    a0 = a2
                    if a0 != width:
                        iCur += 2
                        while iRef < len(ref_flips) and ref_flips[iRef] != width and ref_flips[iRef] <= a0:
                            iRef += 2
                else:
                    # Vertical mode
                    vi = dx + 3  # index 0..6
                    code, code_len = _vtable[vi]
                    bw.insert(code, code_len)
                    a0 = a1
                    if a0 != width:
                        if iRef != 0:
                            iRef -= 2
                        iRef += 1
                        iCur += 1
                        while iRef < len(ref_flips) and ref_flips[iRef] <= a0 and ref_flips[iRef] != width:
                            iRef += 2

        # Swap reference and current
        ref_flips = cur_flips

    bw.flush()
    return bytes(bw.buf)


def make_bb_bitmap(pixel_rows: list, width: int, height: int) -> bytes:
    """Create a complete BB_BITMAP blob (header + G5 data)."""
    g5_data = g5_encode(pixel_rows, width, height)
    # Header: marker(2) + width(2) + height(2) + compressed_size(2)
    header = struct.pack('<HHHH', BB_BITMAP_MARKER, width, height, len(g5_data))
    return header + g5_data


# ---------------------------------------------------------------------------
# Image rendering
# ---------------------------------------------------------------------------

def _find_font(size: int):
    """Try to find a clean monospace font, fall back to default."""
    font_paths = [
        "/System/Library/Fonts/Menlo.ttc",
        "/System/Library/Fonts/Courier.dfont",
        "/System/Library/Fonts/Monaco.dfont",
        "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf",
        "/usr/share/fonts/truetype/liberation/LiberationMono-Bold.ttf",
    ]
    for fp in font_paths:
        if os.path.exists(fp):
            try:
                return ImageFont.truetype(fp, size)
            except Exception:
                continue
    return ImageFont.load_default()


def render_echo_wordmark(width: int, height: int) -> Image.Image:
    """
    Render "ECHO" text centered on a black background (white text).
    For e-paper: white pixels = 1, black pixels = 0 in 1-bpp.
    """
    img = Image.new('1', (width, height), 0)  # black background
    draw = ImageDraw.Draw(img)

    # Find a good font size — target ~60% of the smaller dimension
    target_height = int(min(width, height) * 0.45)
    font_size = target_height
    font = _find_font(font_size)

    # Measure and adjust
    bbox = draw.textbbox((0, 0), "ECHO", font=font)
    text_w = bbox[2] - bbox[0]
    text_h = bbox[3] - bbox[1]

    # Scale font if text is too wide
    if text_w > width * 0.85:
        font_size = int(font_size * (width * 0.85) / text_w)
        font = _find_font(font_size)
        bbox = draw.textbbox((0, 0), "ECHO", font=font)
        text_w = bbox[2] - bbox[0]
        text_h = bbox[3] - bbox[1]

    x = (width - text_w) // 2 - bbox[0]
    y = (height - text_h) // 2 - bbox[1]

    draw.text((x, y), "ECHO", fill=1, font=font)
    return img


def render_qr_code(url: str, width: int, height: int) -> Image.Image:
    """Generate a QR code image at the specified dimensions."""
    qr = qrcode.QRCode(
        version=None,
        error_correction=qrcode.constants.ERROR_CORRECT_L,
        box_size=1,
        border=1,
    )
    qr.add_data(url)
    qr.make(fit=True)

    # qrcode library: white=255, black=0
    qr_img = qr.make_image(fill_color="black", back_color="white").convert('1')

    # Resize to target dimensions
    qr_img = qr_img.resize((width, height), Image.NEAREST)
    return qr_img


def image_to_pixel_rows(img: Image.Image) -> list:
    """
    Convert a PIL '1' mode image to list of bytes rows (MSB-first, 1-bpp).
    In the G5 format: white=1, black=0 (matching the original TRMNL bitmaps).
    """
    width, height = img.size
    row_bytes = (width + 7) // 8
    rows = []
    pixels = img.load()

    for y in range(height):
        row = bytearray(row_bytes)
        for x in range(width):
            if pixels[x, y]:  # white pixel = 1
                row[x >> 3] |= (0x80 >> (x & 7))
        rows.append(bytes(row))

    return rows


# ---------------------------------------------------------------------------
# C header generation
# ---------------------------------------------------------------------------

def format_c_header(var_name: str, data: bytes, width: int, height: int) -> str:
    """Format binary data as a C header file matching the original format."""
    compressed_size = len(data) - 8  # minus 8-byte header
    lines = []
    lines.append(HEADER_COMMENT)
    lines.append("//")
    lines.append(f"// {width} x {height} x 1-bit per pixel")
    lines.append(f"// compressed image data size = {len(data)} bytes")
    lines.append("//")
    lines.append(f"const uint8_t {var_name}[] = {{")

    # Format data bytes 16 per line
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        hex_vals = ','.join(f'0x{b:02x}' for b in chunk)
        if i + 16 >= len(data):
            lines.append(hex_vals + '};')
        else:
            lines.append(hex_vals + ',')

    lines.append('')
    return '\n'.join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    created_files = []

    # Generate logo bitmaps
    for name, spec in BITMAPS.items():
        w, h = spec['width'], spec['height']
        print(f"Generating {name} ({w}x{h})...")

        img = render_echo_wordmark(w, h)
        pixel_rows = image_to_pixel_rows(img)
        bb_data = make_bb_bitmap(pixel_rows, w, h)

        header_text = format_c_header(spec['var'], bb_data, w, h)
        out_path = OUTPUT_DIR / spec['file']
        out_path.write_text(header_text)

        created_files.append((out_path, len(bb_data)))
        print(f"  -> {out_path} ({len(bb_data)} bytes compressed)")

    # Generate QR code
    print(f"Generating wifi_failed_qr ({QR_SPEC['width']}x{QR_SPEC['height']})...")

    qr_img = render_qr_code(QR_SPEC['url'], QR_SPEC['width'], QR_SPEC['height'])
    pixel_rows = image_to_pixel_rows(qr_img)
    bb_data = make_bb_bitmap(pixel_rows, QR_SPEC['width'], QR_SPEC['height'])

    header_text = format_c_header(QR_SPEC['var'], bb_data, QR_SPEC['width'], QR_SPEC['height'])
    out_path = OUTPUT_DIR / QR_SPEC['file']
    out_path.write_text(header_text)

    created_files.append((out_path, len(bb_data)))
    print(f"  -> {out_path} ({len(bb_data)} bytes compressed)")

    # Summary
    print("\n--- Generated files ---")
    for path, size in created_files:
        file_size = path.stat().st_size
        print(f"  {path.name:25s}  {size:6d} bytes (data)  {file_size:6d} bytes (file)")

    print("\nDone.")


if __name__ == '__main__':
    main()
