#!/usr/bin/env python3
"""
PNG to C Header Converter

Converts PNG sprite images to C header files for embedding in firmware.
Outputs a single header file with all sprite data as byte arrays.
"""

import os
import zlib
import base64

SPRITE_DIR = "sprites"
OUTPUT_FILE = "src/sprite_data.h"
STATE_NAMES = [
    "idle",
    "thinking",
    "talking",
    "excited",
    "sleeping",
    "error",
    "alert",
    "working"
]

def png_to_c_array(filename, variable_name):
    """Convert PNG file to C byte array"""
    with open(filename, 'rb') as f:
        data = f.read()

    # Create C array
    lines = []
    lines.append(f"static const uint8_t {variable_name}[] = {{")

    # Format as hex bytes, 12 per line
    for i in range(0, len(data), 12):
        chunk = data[i:i+12]
        hex_bytes = ", ".join(f"0x{b:02x}" for b in chunk)
        if i + 12 < len(data):
            lines.append(f"    {hex_bytes},")
        else:
            lines.append(f"    {hex_bytes}")

    lines.append("};")
    lines.append("")
    lines.append(f"#define {variable_name}_SIZE {len(data)}")
    lines.append("")

    return "\n".join(lines), len(data)

def generate_sprite_header():
    """Generate the sprite data header file"""

    header_parts = []

    # Header guard and includes
    header_parts.append("/**")
    header_parts.append(" * @file sprite_data.h")
    header_parts.append(" * @brief Embedded PNG sprite data for Moltbot states")
    header_parts.append(" *")
    header_parts.append(" * Auto-generated by scripts/png_to_header.py")
    header_parts.append(" */")
    header_parts.append("")
    header_parts.append("#ifndef SPRITE_DATA_H")
    header_parts.append("#define SPRITE_DATA_H")
    header_parts.append("")
    header_parts.append("#include <Arduino.h>")
    header_parts.append("#include \"mqtt_sprite.h\"  // For sprite_state_t")
    header_parts.append("")

    # Sprite structure
    header_parts.append("// Sprite data structure")
    header_parts.append("typedef struct {")
    header_parts.append("    const uint8_t* data;")
    header_parts.append("    size_t size;")
    header_parts.append("} sprite_data_t;")
    header_parts.append("")

    # Convert each PNG to C array
    total_size = 0
    sprite_entries = []

    for state_name in STATE_NAMES:
        png_file = os.path.join(SPRITE_DIR, f"sprite_{state_name}.png")
        var_name = f"sprite_png_{state_name}"

        if os.path.exists(png_file):
            c_array, size = png_to_c_array(png_file, var_name)
            header_parts.append(c_array)
            total_size += size
            sprite_entries.append(f"    {{{var_name}, {var_name}_SIZE}},  // {state_name}")
        else:
            print(f"Warning: {png_file} not found, skipping")

    # Sprite lookup table
    header_parts.append("// Sprite lookup table indexed by state")
    header_parts.append("static const sprite_data_t sprite_table[] = {")
    header_parts.extend(sprite_entries)
    header_parts.append("};")
    header_parts.append("")

    # Helper function declarations
    header_parts.append("// Helper function to get sprite data")
    header_parts.append("inline const sprite_data_t* get_sprite_data(sprite_state_t state) {")
    header_parts.append("    if (state >= 0 && state < (int)(sizeof(sprite_table) / sizeof(sprite_table[0]))) {")
    header_parts.append("        return &sprite_table[state];")
    header_parts.append("    }")
    header_parts.append("    return NULL;")
    header_parts.append("}")
    header_parts.append("")

    # Footer
    header_parts.append("#endif // SPRITE_DATA_H")

    # Write to file
    output_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", OUTPUT_FILE)
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    with open(output_path, 'w') as f:
        f.write("\n".join(header_parts))

    print(f"Generated: {output_path}")
    print(f"Total sprite data size: {total_size} bytes ({total_size / 1024:.1f} KB)")
    print(f"Number of sprites: {len(STATE_NAMES)}")

    return output_path

if __name__ == "__main__":
    print("PNG to C Header Converter")
    print("=" * 40)
    generate_sprite_header()
